"""add password to user model

Revision ID: 450b42d23e58
Revises: 0a3ff60dd67b
Create Date: 2023-04-15 19:42:06.236043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450b42d23e58'
down_revision = '0a3ff60dd67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
