"""add author model

Revision ID: d70f96e5fd19
Revises: 58a8a1decb32
Create Date: 2023-04-22 18:53:56.791763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70f96e5fd19'
down_revision = '58a8a1decb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_author_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_author'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
